inherit SKILL;
mapping *quest = ({

        ([      "short":                "汉水南岸",
                "place":                "/d/shaolin/hanshui1",
        ]),
        ([      "short":                "南阳城",
                "place":                "/d/shaolin/nanyang",
        ]),
        ([      "short":                "汝州城",
                "place":                "/d/shaolin/ruzhou",
        ]),
        ([      "short":                "少室山石阶",
                "place":                "/d/shaolin/shijie2",
        ]),
        ([      "short":                "西长安街",
                "place":                "/d/beijing/xichang1",
        ]),
        ([      "short":                "京城西门",
                "place":                "/d/beijing/ximen",
        ]),
        ([      "short":                "华山村东村口",
                "place":                "/d/village/eexit",
        ]),
        ([      "short":                "华山村碎石路",
                "place":                "/d/village/eroad2",
        ]),
        ([      "short":                "泉州海港口",
                "place":                "/d/quanzhou/haigang",
        ]),
        ([      "short":                "泉州北门",
                "place":                "/d/quanzhou/beimen",
        ]),
        ([      "short":                "武夷山路",
                "place":                "/d/quanzhou/qzroad5",
        ]),
        ([      "short":                "嘉兴南门",
                "place":                "/d/quanzhou/jxnanmen",
        ]),
        ([      "short":                "扬州南大街",
                "place":                "/d/city/nandajie1",
        ]),
        ([      "short":                "岱宗坊",
                "place":                "/d/taishan/daizong",
        ]),
        ([      "short":                "泰山一天门",
                "place":                "/d/taishan/yitian",
        ]),
        ([      "short":                "泰山石经峪",
                "place":                "/d/taishan/shijin",
        ]),
        ([      "short":                "京城海港",
                "place":                "/d/tanggu/haigang",
        ]),
         ([      "short":                "星宿六盘山",
                 "place":                "/d/xingxiu/xxroad3",
        ]),
         ([      "short":                "丝绸之路",
                 "place":                "/d/xingxiu/silk1",
        ]),
         ([      "short":                "武当黄土路",
                 "place":                "/d/wudang/wdroad7",
        ]),
         ([      "short":                "武当山脚下",
                 "place":                "/d/wudang/wdroad8",
        ]),
         ([      "short":                "天山脚下",
                 "place":                "/d/xingxiu/shanjiao",
        ]),
         ([      "short":                "北疆小镇",
                 "place":                "/d/xingxiu/beijiang",
        ]),
         ([      "short":                "赛马场",
                 "place":                "/d/xingxiu/saimachang",
        ]),
         ([      "short":                "华山玉女峰",
                 "place":                "/d/huashan/yunu",
        ]),
         ([      "short":                "华山镇岳宫",
                 "place":                "/d/huashan/zhenyue",
        ]),
         ([      "short":                "华山猢狲愁",
                 "place":                "/d/huashan/husun",
        ]),
         ([      "short":                "华山青柯坪",
                 "place":                "/d/huashan/qingke",
        ]),
         ([      "short":                "华山脚下",
                 "place":                "/d/huashan/path1",
        ]),
         ([      "short":                "明教山脚下",
                 "place":                "/d/mj/shanjiao",
        ]), 
         ([      "short":                "古墓小树林",
                 "place":                "/d/gumu/shulin2",
        ]),
      });

mapping query_quest()
{
  return quest[random(sizeof(quest))];
}

