mapping gems = ([
	"ruby":		"红宝石",
	"topaz":	"黄宝石",
	"sapphire":	"蓝宝石",
	"emerald":	"祖母绿",
	"amethyst":	"紫水晶",
	"diamond":	"水晶钻",
	"skull":	"骷髅头",
	"windjade":	"风魄玉",
	"firejade":	"赤霞玉",	
	"icejade":	"冰薇玉",
	"thunderjade":	"紫晶玉",
	"earthjade":	"黄龙玉",
]);
mapping gems_color = ([
	"ruby":		HIR,
	"topaz":	HIY,
	"sapphire":	HIB,
	"emerald":	HIG,
	"amethyst":	MAG,
	"diamond":	HIW,
	"skull":	WHT,
	"windjade":	GRN,
	"firejade":	RED,	
	"icejade":	CYN,
	"thunderjade":	MAG,
	"earthjade":	YEL,
]);
string *gems_level = ({
	"细碎的",
	"粗糙的",
	"标准的",
	"精致的",
	"完美的",
        "帝王的",
        "魔王的",
        "天圣的",
});
string *gems_level_id = ({
	"chipped",
	"flawed",
	"standard",
	"flawless",
	"prefect",
        "diwang",
        "mowang",
        "tiansheng",
});
mapping weapon_effect = ([
	"ruby":		"使对手的气血受到伤害",
	"topaz":	"使对手的精气受到伤害",
	"sapphire":	"以魔力使对手忙乱",
	"emerald":	"使对手中毒",
	"amethyst":	"提升你的攻击力",
	"diamond":	"提升兵器的破坏力，并摧毁对手的兵器",
	"skull":	"吸取对手的气血和内力",
	"windjade":	"风属性攻击并减少敌人的速度",
	"firejade":	"火属性攻击并减少敌人的防护力",	
	"icejade":	"水属性攻击并减少敌人的命中力",
	"thunderjade":	"雷属性攻击并减少敌人的内力",
	"earthjade":	"土属性攻击并使敌人中毒",
]);
mapping armor_effect = ([
	"ruby":		"战斗中自动恢复气血",
	"topaz":	"战斗中自动恢复精气",
	"sapphire":	"减短你的忙乱时间",
	"emerald":	"让打中你的对手中毒",
	"amethyst":	"提升你的防御力",
	"diamond":	"提升防具的防护力，并减轻你受到的伤害",
	"skull":	"让打中你的对手受伤",
	"windjade":	"会使敌人攻击无效化",
	"firejade":	"使敌人攻击时烧伤",	
	"icejade":	"让敌人被自己的攻击反震",
	"thunderjade":	"会使敌人全身麻痹",
	"earthjade":	"恢复自己的气精",
]);
mapping ring_effect = ([
	"ruby":		"提升你的气血上限",
	"topaz":	"提升你的精气上限",
	"sapphire":	"提升你的内力",
	"emerald":	"提升你的运气",
	"amethyst":	"提升你的身法",
	"diamond":	"提升你的臂力",
	"skull":	"提升魔法石发挥效用的几率",
	"windjade":	"提升自己的速度，防御",
	"firejade":	"暂时提升自己内力并增加精气",	
	"icejade":	"提升自己福缘和像貌",
	"thunderjade":	"提升自己的智力",
	"earthjade":	"恢复自己的食物和水,并增加精力",

]);
