#include <ansi.h>
mapping *wheres=({
          
      (["chinese":                "大理北门",
       "weizhi" :              "/d/dali/northgate",]),  
      (["chinese":                "扬州密林",
       "weizhi" :              "/d/city/jiaowai5",]),  
     (["chinese":                "峨嵋草棚",
       "weizhi" :              "/d/emei/caopeng",]),
     (["chinese":                "扬州西门",
       "weizhi" :              "/d/city/ximen",]),
     (["chinese":                "雪山土路",
       "weizhi" :              "/d/xueshan/tulu2",]),
     (["chinese":                "苏州留园",
       "weizhi" :              "/d/suzhou/liuyuan",]),
     (["chinese":                "苏州寒山寺",
       "weizhi" :              "/d/suzhou/hanshansi",]),
     (["chinese":                "杭州飞来峰",
       "weizhi" :              "/d/hangzhou/feilaifeng",]),
     (["chinese":                "杭州净慈寺",
       "weizhi" :              "/d/hangzhou/jingcisi",]),
     (["chinese":                "杭州翠微亭",
       "weizhi" :              "/d/hangzhou/cuiweiting",]),
     (["chinese":                "杭州聚景园",
       "weizhi" :              "/d/hangzhou/jujingyuan",]),
     (["chinese":                "苗疆易溪部",
       "weizhi" :              "/d/dali/yixibu",]),  
      (["chinese":                "扬州中央广场",
       "weizhi" :              "/d/city/guangchang",]),  
      (["chinese":                "杭州沿湖大道",
       "weizhi" :              "/d/hangzhou/dadao1",]), 
      (["chinese":                "杭州断桥",
       "weizhi" :              "/d/hangzhou/duanqiao",]), 
      (["chinese":                "杭州灵隐寺",
       "weizhi" :              "/d/hangzhou/lingyinsi",]), 
      (["chinese":                "星宿海伊犁",
       "weizhi" :              "/d/xingxiu/beijiang",]), 
      (["chinese":                "武当三天门",
       "weizhi" :              "/d/wudang/santiangate",]), 
      (["chinese":                "峨嵋十二盘",
       "weizhi" :              "/d/emei/shierpan3",]), 
      (["chinese":                "峨嵋千佛庵",
       "weizhi" :              "/d/emei/qianfoan",]), 
      (["chinese":                "峨嵋九十九道拐",
       "weizhi" :              "/d/emei/jsjdg1",]), 
      (["chinese":                "明教厚土旗门",
       "weizhi" :              "/d/mingjiao/htqmen",]), 
      (["chinese":                "明教烈火旗后门",
       "weizhi" :              "/d/mingjiao/lhqhoumen",]), 
      (["chinese":                "福州东门",
       "weizhi" :              "/d/fuzhou/dongmen",]), 
      (["chinese":                "福州北大街",
       "weizhi" :              "/d/fuzhou/beidajie",]), 
      (["chinese":                "星宿海沙漠",
       "weizhi" :              "/d/xingxiu/shamo2",]),
      (["chinese":                "少林寺石阶",
       "weizhi" :              "/d/shaolin/shijie4",]),
      (["chinese":                "襄阳石阶",
       "weizhi" :              "/d/xiangyang/walle1",]),
      (["chinese":                "华山猢狲愁",
       "weizhi" :              "/d/huashan/husun",]),
      (["chinese":                "华山玉女峰",
       "weizhi" :              "/d/huashan/yunu",]),
      (["chinese":                "慕容小径",
       "weizhi" :              "/d/mr/xiaojing1-2",]),
      (["chinese":                "慕容柳树林",
       "weizhi" :              "/d/mr/liulin",]),
      (["chinese":                "大理大和街",
       "weizhi" :              "/d/dali/dahejiewest",]),
      (["chinese":                "苏州城北门",
       "weizhi" :              "/d/suzhou/beimen",]),
      (["chinese":                "苏州城玄妙观",
       "weizhi" :              "/d/suzhou/xuanmiao",]),
      (["chinese":                "少林寺山门殿",
       "weizhi" :              "/d/shaolin/smdian",]),
      (["chinese":                "少林寺走廊",
       "weizhi" :              "/d/shaolin/zoulang7",]),
      (["chinese":                "武当山路",
       "weizhi" :              "/d/wudang/shanlu3",]),
      (["chinese":                "少林寺般若堂九部",
       "weizhi" :              "/d/shaolin/banruo9",]),
      (["chinese":                "雪山山脚",
       "weizhi" :              "/d/xueshan/shanjiao",]),
      (["chinese":                "峨嵋九老洞",
       "weizhi" :              "/d/emei/jiulaodong",]),
       (["chinese":                "峨嵋古德林",
       "weizhi" :              "/d/emei/gudelin1",]),
       (["chinese":                "函古关",
       "weizhi" :              "/d/city4/hanguguan",]),
       (["chinese":                "终南山口",
       "weizhi" :              "/d/city4/zhongnan",]),
       (["chinese":                "闽江",
       "weizhi" :              "/d/fuzhou/fzroad8",]),
       (["chinese":                "汉水南岸",
       "weizhi" :              "/d/shaolin/hanshui1",]),
       (["chinese":                "中条山密林",
       "weizhi" :              "/d/huashan/jzroad5",]),
       (["chinese":                "天山脚下",
       "weizhi" :              "/d/xingxiu/shanjiao",]),
       (["chinese":                "华山脚下",
       "weizhi" :              "/d/huashan/path1",]),
       (["chinese":                "平定州",
       "weizhi" :              "/d/heimuya/pingdingzhou",]),
       (["chinese":                "乱石坡",
       "weizhi" :              "/d/heimuya/road1",]),      
       (["chinese":                "华山村南村口",
       "weizhi":                "/d/village/sexit",]),
       (["chinese":                "闽赣古道",
       "weizhi":                "/d/fuzhou/fzroad7",]),
       (["chinese":                "玉皇顶",
       "weizhi":               "/d/taishan/yuhuang",]),
       (["chinese":                "六盘山",
       "weizhi":                "/d/xingxiu/xxroad3",]),
       (["chinese":                "天山山路",
       "weizhi":                "/d/xingxiu/tianroad1",]),
       (["chinese":                "嘉峪关",
       "weizhi":                "/d/xingxiu/jiayuguan",]),
       (["chinese":                "西单北大街",
       "weizhi":                "/d/beijing/xidan1",]),
       (["chinese":                "武道场",
       "weizhi":                "/d/city/wudao4",]),
       (["chinese":                "王府井大街",
       "weizhi":                "/d/beijing/wangfu2",]),
       (["chinese":                "全真教碑",
       "weizhi":                "/d/quanzhen/jiaobei",]),
       (["chinese":                "老妪岩",
       "weizhi":                "/d/gumu/juyan",]),
       (["chinese":                "老龙头",
       "weizhi":                "/d/guanwai/laolongtou",]),
       (["chinese":                "嘉兴城",
       "weizhi":                "/d/quanzhou/jiaxing",]),
       (["chinese":                "扬州西门",
       "weizhi":                "/d/city/ximen",]),
       (["chinese":                "仙霞岭",
       "weizhi":                "/d/fuzhou/fzroad1",]),
       (["chinese":                "宁远",
       "weizhi":                "/d/taishan/yitian",]),
       (["chinese":                "小土屋",
       "weizhi":                "/d/guanwai/tuwu",]),
       (["chinese":                "下关城",
       "weizhi":                "/d/dali/xiaguan",]),
       (["chinese":                "李子箐石林",
        "weizhi":                "/d/dali/shilin1",]),
        (["chinese":                "大叠水瀑布",
        "weizhi":                "/d/dali/dadieshui",]),
        (["chinese":                "罗伽甸",
        "weizhi":                "/d/dali/luojiadian",]),
        (["chinese":                "阳宗镇",
        "weizhi":                "/d/dali/yangzong",]),
        (["chinese":                "太室阙",
        "weizhi":                "/d/songshan/taishique",]),
        (["chinese":                "少林石阶",
        "weizhi":                "/d/shaolin/shijie7",]),
        (["chinese":                "铁梁峡",
        "weizhi":                "/d/songshan/tieliang",]),
        (["chinese":                "峻极禅院山门",
        "weizhi":                "/d/songshan/junjigate",]),
        (["chinese":                "神禾原",
        "weizhi":                "/d/gumu/shenheyuan",]),
        (["chinese":                "终南山大校场",
        "weizhi":                "/d/gumu/daxiaochang",]),
        (["chinese":                "金锁关",
        "weizhi":                "/d/huashan/jinsuo",]),
        (["chinese":                "平心石",
        "weizhi":                "/d/huashan/pingxinshi",]),
        (["chinese":                "千尺幢",
        "weizhi":                "/d/huashan/qianchi",]),
        (["chinese":                "山洪瀑布",
        "weizhi":                "/d/huashan/shanhongpb",]),
        (["chinese":                "清音阁",
        "weizhi":                "/d/emei/qingyinge",]),
        (["chinese":                "十二盘",
        "weizhi":                "/d/emei/shierpan1",]),
        (["chinese":                "九老洞口",
        "weizhi":                "/d/emei/jldongkou",]),
        (["chinese":                "九十九道拐",
        "weizhi":                "/d/emei/jsjdg2",]),
        (["chinese":                "千佛庵",
        "weizhi":                "/d/emei/qianfoan",]),
        (["chinese":                "终南山空地",
        "weizhi":                "/d/gumu/kongdi",]),
        (["chinese":                "终南山主峰",
        "weizhi":                "/d/gumu/zhufeng",]),
        (["chinese":                "悬天崖",
        "weizhi":                "/d/mingjiao/shanlu3",]),
         (["chinese":                "烈火旗大门",
        "weizhi":                "/d/mingjiao/lhqmen",]),
        (["chinese":                "雪山寺山门",
        "weizhi":                "/d/xueshan/shanmen",]),
        (["chinese":                "洪水旗大门",
        "weizhi":                "/d/mingjiao/hsqmen",]),
        (["chinese":                "洪水旗大门",
        "weizhi":                "/d/mingjiao/hsqmen",]),
        (["chinese":                "北大街",
        "weizhi":                "/d/mingjiao/hsqmen",]),
        (["chinese":                "青石大道",
        "weizhi":                "/d/wudang/wdroad1",]),
        (["chinese":                "关洛道",
        "weizhi":                "/d/city4/road1",]),
        (["chinese":                "大驿道",
        "weizhi":                "/d/taishan/yidao",]),
        (["chinese":                "官道",
        "weizhi":                "/d/quanzhen/guandao2",]),
        (["chinese":                "东街",
        "weizhi":                "/d/quanzhen/dongjie",]),
        (["chinese":                "富家大门",
        "weizhi":                "/d/quanzhen/fu-damen",]),
        (["chinese":                "山路",
        "weizhi":                "/d/quanzhen/shanlu1",]),
        (["chinese":                "小村庄",
        "weizhi":                "/d/quanzhen/xiaocun",]),
        (["chinese":                "星宿海",
        "weizhi":                "/d/xingxiu/xxh2",]),
        (["chinese":                "天山脚下",
        "weizhi":                "/d/xingxiu/shanjiao",]),
        (["chinese":                "丝绸之路",
        "weizhi":                "/d/xingxiu/silk2",]),
        (["chinese":                "长安城西门",
        "weizhi":                "/d/city4/westgate",]),
        (["chinese":                "长安城东门",
        "weizhi":                "/d/city4/eastgate",]),
        (["chinese":                "城东门",
        "weizhi":                "/d/city4/eastgate",]),
        (["chinese":                "上天梯",
        "weizhi":                "/d/huashan/shangtianti",]),
        (["chinese":                "树林",
        "weizhi":                "/d/xiaoyao/shulin3",]),
        (["chinese":                "南大街",
        "weizhi":                "/d/xiaoyao/shulin3",]),
        
           });


