// 门派武功列表 (by xbd)

mapping *ps = ({
	([	"party": "wudang",
		"status": ([
			"party": "wudang",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"taiji-shengong": 200,
			"taoism": 200,
			"tiyunzong": 200,
			"taiji-quan": 200,
			"taiji-jian": 200,
			"yitian-tulong": 200,
			"wudang-array": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "taiji-shengong",
			"dodge": "tiyunzong",
			"unarmed": "taiji-quan",
			"sword": "taiji-jian",
			"parry": "taiji-quan",
			"array": "wudang-aray",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "huashan",
		"status": ([
			"party": "huashan",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"zixia-shengong": 200,
			"zhengqijue": 200,
			"feiyan-huixiang": 200,
			"poyu-quan": 200,
			"hunyuan-zhang": 200,
			"lonely-sword": 200,
			"huashan-sword": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "zixia-shengong",
			"dodge": "feiyan-huixiang",
			"unarmed": "poyu-quan",
			"strike": "hunyuan-zhang",
			"sword": "lonely-sword",
			"parry": "lonely-sword",]),
		"skill_prepare": ([
			"unarmed": "poyu-quan",
			"strike": "hunyuan-zhang",]),
	]),
	([	"party": "lingjiu",
		"status": ([
			"party": "lingjiu",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"bahuang-gong": 200,
			"beiming-shengong": 200,
			"yangyanshu": 200,
			"lingboweibu": 200,
			"zhemei-shou": 200,
			"liuyang-zhang": 200,
			"tianyu-qijian": 200,
			"ruyi-dao": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "bahuang-gong",
			"dodge": "lingboweibu",
			"unarmed": "zhemei-shou",
			"strike": "liuyang-zhang",
			"sword": "tianyu-qijian",
			"parry": "lingboweibu",]),
		"skill_prepare": ([
			"unarmed": "zhemei-shou",
			"strike": "liuyang-zhang",]),
	]),
	([	"party": "taohua",
		"status": ([
			"party": "taohua",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"bibo-shengong": 200,
			"qimen-wuxing": 200,
			"count": 200,
			"anying-fuxiang": 200,
			"tanzhi-shentong": 200,
			"lanhua-shou": 200,
			"luoying-zhang": 200,
			"xuanfeng-leg": 200,
			"yuxiao-jian": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "bibo-shengong",
			"dodge": "anying-fuxiang",
			"unarmed": "xuanfeng-leg",
			"strike": "luoying-zhang",
			"finger": "tanzhi-shentong",
			"hand": "lanhua-shou",
			"sword": "yuxiao-jian",
			"parry": "yuxiao-jian",]),
		"skill_prepare": ([
			"finger": "tanzhi-shentong",
			"hand": "lanhua-shou",]),
	]),
	([	"party": "tiandihui",
		"status": ([
			"party": "tiandihui",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"yunlong-shengong": 200,
			"yunlong-xinfa": 200,
			"yunlong-shenfa": 200,
			"yunlong-zhua": 200,
			"yunlong-shou": 200,
			"houquan": 200,
			"yunlong-jian": 200,
			"yunlong-bian": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "yunlong-shengong",
			"dodge": "yunlong-shenfa",
			"unarmed": "houquan",
			"claw": "yunlong-zhua",
			"hand": "yunlong-shou",
			"sword": "yunlong-jian",
			"parry": "yunlong-jian",]),
		"skill_prepare": ([
			"claw": "yunlong-zhua",
			"hand": "yunlong-shou",]),
	]),
	([	"party": "mingjiao",
		"status": ([
			"party": "mingjiao",
			"family/family_name": "明教",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"jiuyang-shengong": 200,
			"shenghuo-shengong": 200,
			"qiankun-danuoyi": 200,
			"qingfu-shenfa": 200,
			"qishang-quan": 200,
			"hanbing-mianzhang": 200,
			"sougu": 200,
			"shenghuo-ling": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "jiuyang-shengong",
			"dodge": "qingfu-shenfa",
			"unarmed": "qishang-quan",
			"strike": "hanbing-mianzhang",
			"claw": "sougu",
			"sword": "shenghuo-ling",
			"parry": "qiankun-danuoyi",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "gumu",
		"status": ([
			"party": "gumu",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"yunv-xinfa": 200,
			"qufeng": 200,
			"yunv-shenfa": 200,
			"anranxiaohun-zhang": 200,
			"meinv-quan": 200,
			"tianluo-diwang": 200,
			"yunv-jian": 200,
			"quanzhen-jian": 200,
			"xuantie-sword": 200,
			"qixing-array": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "yunv-xinfa",
			"dodge": "yunv-shenfa",
			"unarmed": "anranxiaohun-zhang",
			"strike": "tianluo-diwang",
			"cuff": "meinv-quan",
			"sword": "yunv-jian",
			"parry": "yunv-jian",
			"array": "qixing-array",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "gaibang",
		"status": ([
			"party": "gaibang",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"huntian-qigong": 200,
			"begging": 200,
			"xiaoyaoyou": 200,
			"xianglong-zhang": 200,
			"dagou-bang": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "huntian-qigong",
			"dodge": "xiaoyaoyou",
			"unarmed": "xianglong-zhang",
			"staff": "dagou-bang",
			"parry": "dagou-bang",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "quanzhen",
		"status": ([
			"party": "quanzhen",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"xiantian-qigong": 200,
			"taoism": 200,
			"jinyan-gong": 200,
			"haotian-zhang": 200,
			"sun-finger": 200,
			"quanzhen-jian": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "xiantian-qigong",
			"dodge": "jinyan-gong",
			"strike": "haotian-zhang",
			"finger": "sun-finger",
			"sword": "quanzhen-jian",
			"parry": "quanzhen-jian",]),
		"skill_prepare": ([
			"strike": "haotian-zhang",
			"finger": "sun-finger",]),
	]),
	([	"party": "dali",
		"status": ([
			"party": "dali",
			"no_accept": 1,
			"no_fight": 1,
			"no_weapon": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"kurong-changong": 200,
			"buddhism": 200,
			"tiannan-step": 200,
			"six-finger": 200,
			"sun-finger": 200,
			"yiyang-zhi": 200,
			"duanjia-sword": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "kurong-changong",
			"dodge": "tiannan-step",
			"unarmed": "six-finger",
			"finger": "sun-finger",
			"sword": "duanjia-sword",
			"parry": "six-finger",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "tiezhang",
		"status": ([
			"party": "tiezhang",
			"no_accept": 1,
			"no_fight": 1,
			"no_weapon": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"guiyuan-tunafa": 200,
			"shuishangpiao": 200,
			"tiezhang-zhangfa": 200,
			"duanyun-fu": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "guiyuan-tunafa",
			"dodge": "shuishangpiao",
			"unarmed": "tiezhang-zhangfa",
			"strike": "tiezhang-zhangfa",
			"axe": "duanyun-fu",
			"parry": "tiezhang-zhangfa",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "murong",
		"status": ([
			"party": "murong",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"shenyuan-gong": 200,
			"douzhuan-xingyi": 200,
			"yanling-shenfa": 200,
			"canhe-zhi": 200,
			"xingyi-zhang": 200,
			"murong-jianfa": 200,
			"murong-daofa": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "shenyuan-gong",
			"dodge": "yanling-shenfa",
			"finger": "canhe-zhi",
			"strike": "xingyi-zhang",
			"sword": "murong-jianfa",
			"parry": "douzhuan-xingyi",]),
		"skill_prepare": ([
			"finger": "canhe-zhi",
			"strike": "xingyi-zhang",]),
	]),
	([	"party": "kunlun",
		"status": ([
			"party": "kunlun",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"xuantian-wuji": 200,
			"art": 200,
			"kunlun-shenfa": 200,
			"kunlun-zhang": 200,
			"chuanyun-tui": 200,
			"zhentian-quan": 200,
			"liangyi-jian": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "xuantian-wuji",
			"dodge": "kunlun-shenfa",
			"strike": "kunlun-zhang",
			"unarmed": "chuanyun-tui",
			"cuff": "zhentian-quan",
			"sword": "liangyi-jian",
			"parry": "liangyi-jian",]),
		"skill_prepare": ([
			"unarmed": "chuanyun-tui",
			"cuff": "zhentian-quan",]),
	]),
	([	"party": "lingxiao",
		"status": ([
			"party": "lingxiao",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"bingxue-xinfa": 200,
			"snowstep": 200,
			"snow-zhang": 200,
			"xueshan-sword": 200,
			"jinwu-blade": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "bingxue-xinfa",
			"dodge": "snowstep",
			"unarmed": "snow-zhang",
			"sword": "xueshan-sword",
			"parry": "xueshan-sword",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "wdjiao",
		"status": ([
			"party": "wdjiao",
			"family/family_name": "五毒教",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"wudu-shengong": 200,
			"duji": 200,
			"ruanhong-zhusuo": 200,
			"wudu-yanluobu": 200,
			"qianzhu-wandushou": 200,
			"wudu-goufa": 200,
			"wudu-bian": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "wudu-shengong",
			"dodge": "wudu-yanluobu",
			"unarmed": "qianzhu-wandushou",
			"sword": "wudu-goufa",
			"whip": "ruanhong-zhusuo",
			"parry": "wudu-goufa",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "baituo",
		"status": ([
			"party": "baituo",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"hamagong": 200,
			"training": 200,
			"chanchu-bufa": 100,
			"shexing-diaoshou": 100,
			"hamashengong": 100,
       "lingshe-quan": 100,
       "lingshe-zhangfa": 100,
			"qixian-wuxingjian": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "hamagong",
			"dodge": "chanchu-bufa",
			"strike": "hamashengong",
                        "cuff": "lingshe-quan",
			"staff": "lingshe-zhangfa",
			"parry": "lingshe-zhangfa",
                        "unarmed": "shexing-diaoshou",
			"hand": "shexing-diaoshou",]),
		"skill_prepare": ([ ]),
	]),

	([	"party": "emei",
		"status": ([
			"party": "emei",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"linji-zhuang": 100,
			"mahayana": 200,
      "persuading": 200,
			"zhutian-bu": 100,
			"yanxing-dao": 100,
			"huifeng-jian": 100,
			"jinding-zhang": 100,
      "bagua-zhang": 100,
       "bagua-dao": 100,
			"tiangang-zhi": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "linji-zhuang",
			"dodge": "zhutian-bu",
			"finger": "tiangang-zhi",
			"strike": "jinding-zhang",
			"sword": "huifeng-jian",
			"parry": "huifeng-jian",]),
		"skill_prepare": ([ ]),
	]),
	
	
	([	"party": "xiaoyao",
		"status": ([
			"party": "xiaoyao",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"bahuang-gong": 100,
			"beiming-shengong": 100,
			"yangyanshu": 200,
			"lingboweibu": 100,
			"zhemei-shou": 100,
			"liuyang-zhang": 100,
			"tianyu-qijian": 100,
      "panyang-zhang": 100,
      "qingyun-shou": 100,
			"ruyi-dao": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "beiming-shengong",
			"dodge": "lingboweibu",
			"unarmed": "zhemei-shou",
			"strike": "liuyang-zhang",
			"blade": "ruyi-dao",
			"parry": "lingboweibu",]),
		"skill_prepare": ([
			"unarmed": "zhemei-shou",
			"strike": "liuyang-zhang",]),
	]),
	

	([	"party": "mizong",
		"status": ([
			"party": "mizong",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"longxiang": 100,
			"xiaowuxiang": 100,
			"lamaism": 200,
      "necromancy": 200,
			"yujiamu-quan": 100,
			"tanzhi-shentong": 100,
			"dashou-yin": 100,
			"huoyan-dao": 100,
			"xiangmo-chu": 100,
     "shenkong-xing": 100,
     "xue-dao": 100,
      "riyue-lun": 100,
			"mingwang-jian": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "xiaowuxiang",
			"dodge": "shenkong-xing",
			"unarmed": "yujiamu-quan",
			"strike": "huoyan-dao",
			"cuff": "yujiamu-quan",
			"hand": "dashou-yin",
			"parry": "huoyan-dao",]),
		"skill_prepare": ([
			"strike": "huoyan-dao",
			"cuff": "yujiamu-quan",
			"hand": "dashou-yin",]),
	]),
	
	
	([	"party": "xingxiu",
		"status": ([
			"party": "xingxiu",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"huagong-dafa": 100,
			"poison": 200,
			"zhaixinggong": 100,
			"sanyin-wugongzhao": 100,
			"feixing-shu": 100,
			"chanhun-suo": 100,
			"tianshan-zhang": 100,
			"chousui-zhang": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "huagong-dafa",
			"dodge": "zhaixinggong",
			"strike": "chousui-zhang",
			"claw": "sanying-wugongzhao",
			"throwing": "feixing-shu",
			"staff": "tianshan-zhang",
			"whip": "chanhun-suo",
			"parry": "chousui-zhang",]),
		"skill_prepare": ([
			"strike": "chousui-zhang",
			"claw": "sanying-wugongzhao",]),
	]),
	
	([	"party": "feitian",
		"status": ([
			"party": "feitian",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"shayi-xinfa": 100,
			"shayi": 200,
			"wuxing-dun": 100,
			"aikido": 100,
			"xuanhualiu-quanfa": 100,
			"shiren-quanfa": 100,
			"shiren-jianfa": 100,
      "feitian-yujianliu": 100,
			"huoxinliu-jianfa": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "shayi-xinfa",
			"dodge": "wuxing-dun",
			"unarmed": "xuanhualiu-quanfa",
			"cuff": "shiren-quanfa",
			"blade": "feitian-yujianliu",
			"parry": "feitian-yujianliu",]),
		"skill_prepare": ([ ]),
	]),
	
	([	"party": "shenlong",
		"status": ([
			"party": "shenlong",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"shenlong-xinfa": 100,
			"zhaosheshu": 200,
			"yixingbu": 100,
			"shenlong-bashi": 100,
			"shedao-qigong": 100,
			"huagu-mianzhang": 100,
			"shenlong-tuifa": 100,
			"dulong-shenzhua": 100,
			"xuanming-zhang": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "shenlong-xinfa",
			"dodge": "yixingbu",
			"strike": "huagu-mianzhang",
			"hand": "shenlong-bashi",
			"claw": "dulong-shenzhua",
			"staff": "shedao-qigong",
			"parry": "shenlong-bashi",
			"leg": "shenlong-tuifa",]),
		"skill_prepare": ([
			"strike": "huagu-mianzhang",
			"hand": "shenlong-bashi",]),
	]),
	
	([	"party": "tangmen",
		"status": ([
			"party": "tangmen",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"biyun-xinfa": 100,
			"qiulinshiye": 100,
			"zimu-zhen": 100,
			"biye-wu": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "biyun-xinfa",
			"dodge": "qiulinshiye",
			"unarmed": "biye-wu",
			"strike": "biye-wu",
                        "throwing": "zimu-zhen",
			"parry": "zimu-zhen",]),
		"skill_prepare": ([ ]),
	]),
	
	([	"party": "riyue",
		"status": ([
			"party": "riyue",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"kuihua-xinfa": 100,
			"kuihua-dafa": 100,
			"kuihua-feiying": 100,
			"pixie-jian": 100,
                        "tmdafa": 200,
                        "tmzhang": 100,
                        "tmjian": 100,
                        "tmdao": 100,
                        "tmdafa": 100,
                        "pmshenfa": 100,
			"changquan": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "kuihua-xinfa",
			"dodge": "kuihua-feiying",
			"unarmed": "changquan",
			"sword": "kuihua-dafa",
			"parry": "kuihua-dafa",]),
		"skill_prepare": ([ ]),
        ]),
	

	
	([	"party": "shaolin",
		"status": ([
			"party": "shaolin",
			"no_accept": 1,
			"no_fight": 1,
			"no_weapon": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"hunyuan-yiqi": 100,
			"buddhism": 200,
			"shaolin-shenfa": 100,
			"nianhua-zhi": 100,
			"sanhua-zhang": 100,
			"fengyun-shou": 100,
                        "longzhua-gong": 100,
                        "weituo-zhang": 100,
                        "shaolin-tantui": 100,                        
                        "jingang-zhang": 100,
                        "jimie-zhua": 100,
                        "duoluoye-zhi": 100,
                        "mohe-zhi": 100,
                        "boluomi-shou": 100,
                        "yijinjing": 100,
                        "cibei-dao": 100,
                        "damo-jian": 100,
                        "luohan-quan": 100,
                        "pudu-zhang": 100,             
                        "wuying-jian": 300,
                        "qianye-shou": 100,
                        "riyue-bian": 100, 
                        "weituo-gun": 100,
                        	"weituo-chu": 100,
                        "wuchang-zhang": 100,
			"banruo-zhang": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "yijinjing",
			"dodge": "shaolin-shenfa",
			"finger": "nianhua-zhi",
			"cuff": "luohan-quan",
			"strike": "sanhua-zhang",
                        "hand": "fengyun-shou",
                        "blade": "cibei-dao",
                        "club": "weituo-chu",
                        "staff": "weituo-gun",
                        "sword": "wuying-jian",
                        "whip": "riyue-bian",
                        "claw": "longzhua-gong",
			"parry": "nianhua-zhi",]),
		"skill_prepare": ([
			"finger": "nianhua-zhi",
			"strike": "sanhua-zhang",]),
	]),




});
