inherit SKILL;
#include <ansi.h>;
//这是星星做来让新手熟悉地图用的任务
//星星（lywin）2000/4/30
mapping *quest = ({
        ([      "quest":   "马超兴",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "武将",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "官兵",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "郭靖",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "店小二",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "冼老板",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "王五",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "钱眼开",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "马夫",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "流氓",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "流氓头",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "朱熹",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "杨永福",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "曾柔",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "平一指",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "药铺伙计","exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "铁匠",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "挑夫",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "趟子手",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "海公公",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "小桂子",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "程玉环",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "谭友纪",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "程药发",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "衙役",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "史青山",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "游方道人","exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "陈有德",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "家丁",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "管家",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "崔员外",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "崔莺莺",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "红娘",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "封弓影",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "蜜蜂",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "桃花村长","exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "桃花童",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "男孩",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "赵敏",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "孙三毁",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "赵一伤",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "钱二败",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "李四摧",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "吴六破",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "周五输",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "王八衰",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "郑七灭",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "史松",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "空空儿",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "韦小宝",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "唐楠",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "香菱",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "小混混",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "哈巴狗",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "胖头陀",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "段誉",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "阿庆嫂",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "韦春芳",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "龟公",    "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "茅十八",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
        ([      "quest":   "欧阳克",  "exp_bonus":random(10)+30,"pot_bonus": random(8)+10  ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];

}
