// qslist5000.c

inherit SKILL;
#include <ansi.h>;
mapping *quest = ({
        ([      "quest":                "肥肥",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "管家",
                "quest_type":           "杀",
                "time":                 280,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "李教头",
                "quest_type":           "杀",
                "time":                 480,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "花花公子",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "小山贼",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "山贼",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "仕卫", 
                "quest_type":           "杀",
                "time":                 480,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "舞蛇人",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "程药发",
                "quest_type":           "杀",
                "time":                 480,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "崔员外",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "管家",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "流氓",
                "quest_type":           "杀",
                "time":                 280,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "流氓头",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "冼老板",
                "quest_type":           "杀",
                "time":                 580,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "小桂子",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "喇嘛",
                "quest_type":           "杀",
                "time":                 580,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "老鸨婆",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "小流氓",
                "quest_type":           "杀",
                "time":                 280,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "仆役",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "吴之荣",
                "quest_type":           "杀",
                "time":                 480,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "小贼",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "「平通镖局」镖头",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "恶奴",
                "quest_type":           "杀",
                "time":                 480,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "贵公子",
                "quest_type":           "杀",
                "time":                 480,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "何红药",
                "quest_type":           "杀",
                "time":                 680,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "祭司",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "神农帮弟子",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "无量剑弟子",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "段天德",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "刀客",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "剑客",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "蒙面人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "日月神教教徒",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "马青雄",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "马贼",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "蒙面人",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "钱青健",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "沈青刚",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "吴青烈",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "西夏兵",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "李铁嘴",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "校尉",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "一品堂武士",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "地痞",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "倭寇",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "年轻女弟子",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "进喜儿",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "土匪",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "土匪头",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "小土匪",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "巴依",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "星宿派钹手",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "采花子",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "星宿派鼓手",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "星宿派号手",
                "quest_type":           "杀",
                "time":                 380,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "守寺僧兵",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),
        ([      "quest":                "小喇嘛",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            65,
                "pot_bonus":            45,
                "score" :               20
        ]),

});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
