// qslist8000.c

inherit SKILL;
#include <ansi.h>;
mapping *quest = ({
        ([      "quest":                "肥肥",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "劳德诺",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "管家",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "李教头",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "花花公子",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小山贼",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "山贼",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "山贼头",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "仕卫", 
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "舞蛇人",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "程药发",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "崔员外",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "管家",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "王五",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "林平之",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "流氓",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "流氓头",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "平一指",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "空空儿",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "冼老板",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小桂子",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "海公公",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "康亲王",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "老鸨婆",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小流氓",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "仆役",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "史松",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "吴之荣",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "吴天德",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小贼",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "「平通镖局」镖头",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "段无畏",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "恶奴",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "管家",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "贵公子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "何红药",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "祭司",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "老祭司",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "乌夷老祭司",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "神农帮弟子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "无量剑弟子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "族头人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "族长",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "老朝奉",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "忽伦大虎",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "忽伦二虎",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "忽伦三虎",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "忽伦四虎",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "阎基",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "段天德",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "大金兵",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "完颜洪烈",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "完颜康",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "褚圆",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "刀客",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "管家",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "剑客",
                "quest_type":           "杀",
                "time":                 100,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "李可秀",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "龙骏",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "蒙面人",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "成德殿殿下弟子",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "日月神教教徒",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "鲁连荣",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "侯通海",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "梁子翁",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "马青雄",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "马贼",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "蒙面人",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "彭连虎",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "钱青健",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "沙通天",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "沈青刚",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "吴青烈",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "西夏兵",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "李铁嘴",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "石人武士",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "校尉",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "西夏兵",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "一品堂武士",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "高山王",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "方人智",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "洪人雄",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "侯人英",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "吉人通",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "贾人达",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "罗人杰",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "申人俊",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "于人豪",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "余人彦",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "地痞",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "红毛鬼",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "李莫愁",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "倭寇",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "游讯",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "行者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "年轻女弟子",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "老者",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "章老三",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "土匪",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "土匪头",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小土匪",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "巴依",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "星宿派钹手",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "采花子",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "星宿派鼓手",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "星宿派号手",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小喇嘛",
                "quest_type":           "杀",
                "time":                 200,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "守寺僧兵",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "李教头",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "阿紫",
                "quest_type":           "杀",
                "time":                 400,
                "exp_bonus":            76,
                "pot_bonus":            50,
                "score" :               20
        ]),

});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

