// qwlist5000.c

inherit SKILL;
#include <ansi.h>;
mapping *quest = ({
        ([      "quest":                "Å£Æ¤¾Æ´ü",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "°×É«³¤ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "º£¿Ú´óÍë",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "²ÝÝ®",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "²ñ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "²ñµ¶",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "´óµ¶",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "½ðÉßµ¨",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "ÇàÉßµ¨",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "ÇàÉ«Ë¿ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Éß±Þ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "Éßµ¨¸à",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            6,
                "pot_bonus":            3,
                "score" :               20
        ]),
        ([      "quest":                "ÉßÆ¤",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            6,
                "pot_bonus":            3,
                "score" :               20
        ]),
        ([      "quest":                "ÉßÈâ",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ðå»¨Ð¬",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÍÃÈâ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "°×É«³¤ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "º£¿Ú´óÍë",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "µ°¸â",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ä¾²ñ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¶¹½¬",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Éßµ¨·Û",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÒýÂ·ÉñÉß",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÉßÕÈ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            54,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ðå»¨Ð¬",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "²ÝÐ¬",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ðå»¨Ð¡Ð¬",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "½ð½äÖ¸",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¹·Æ¤",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            54,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ºìÉÕ¹·Èâ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¾ü·þ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ãæ¾ß",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "½ðÏîÁ´",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÀÎ·¿Ô¿³×",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "ÑÃÒÛ·þ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Öñ°ô",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "°ü×Ó",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Öñ°ô",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "´óµ¶",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "·÷³¾",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "½ðÒ¶",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ºÚÁú±Þ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "½õ¶Ð",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            26,
                "score" :               20
        ]),
        ([      "quest":                "±ùÌÇºùÂ«",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÍÀµ¶",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ñü´ø",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ò©·Û",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "³ñÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "´Ö²¼ÒÂ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "°ÚÒÄ¶ÌÈ¹",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÇàÉ«µÀÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¶·Åñ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¶ÔñÆ¹Ó×Ó",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "»¢Æ¤",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "»ÆÒÂ¾ü·þ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¿³µ¶",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Õ­ñÌ°À",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "±´¿ÇÏîÁ´",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Âùµ¶",
                "quest_type":           "Ñ°",
                "time":                 700,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "Ã«Ìº",
                "quest_type":           "Ñ°",
                "time":                 700,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "°×É´ÌôÏßÏâ±ßÈ¹",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ì¨ÒÄ¶ÌÈ¹",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ìú¼×",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            112,
                "pot_bonus":            9,
                "score" :               20
        ]),
        ([      "quest":                "Í²È¹",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ì¨ÒÄÍ·½í",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÎÚÒÄ³¤È¹",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÎÚÒÄ´ó÷â",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            54,
                "pot_bonus":            26,
                "score" :               20
        ]),
        ([      "quest":                "°×ÒÂ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "°×³ñÉÀ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ô²ÁìÐ¡°À",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "·ÄÉ´»ú",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "·÷³¾",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Èí½£",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Æ¤Ñü´ø",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "µ­»ÆÉÀ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "²Ëµ¶",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Çà²¼³¤ÉÀ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ôÂôÄ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÐÜµ¨¸É",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "ÊìÌú±âµ£",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¸Ë³Ó",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¼âµ¶",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¾Å½Ú±Þ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "¶Ìµ¶",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÓÍÖ½ÕÛÉÈ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ôÕ×Ó",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ºì³ñÐ¡É¼",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "µØÀÎÔ¿³×",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ôæºì¶ÐÃæÆ¤ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ðå»¨Õë",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "´óÕäÖé",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "×Ï³ñÉÀ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "×Ï½ð´¸",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "É¥ÃÅ¸«",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¸ð²¼³¤ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "·ÖË®´Ì",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "Èý¹É²æ",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "´ó¸«Í·",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "Ò¹ÐÐË®¿¿",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "ÌúÇÂ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "³¤ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¶·Åñ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "±ùÑ©ôä´ä¸â",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ô¿³×",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÇàÒÂ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ËáÃ·ÌÀ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ºÚÉ«³¤ÉÀ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ïÙÌúÅÐ¹Ù±Ê",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "ÐåÃ·ÇàÒÂ",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ºì³ñ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÎÞÓÇºì»¨",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÄÏº£ÉñÄ¾",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "ÓÍ²¼°ü",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "°×²¼³¤ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ìú±³ÐÄ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "³¤±Þ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "³¤½£",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ìøÕÈ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "´ó»¹µ¤",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "´ó°×Óã",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "Óã¹Ç",
                "quest_type":           "Ñ°",
                "time":                 700,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "Ê¬¹Ç",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ñô¶¥ÌìÒÅ¹Ç",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "Ñô·òÈËÒÅ¹Ç",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "Æ¤Ñü´ø",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "ÒÐÌì½£",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "Ñô½ÌÖ÷ÒÅÐÅ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "½õ¶Ð",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ºÉÀ¼»ðÇ¹",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "ìøÕÈ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "½ð±ßºÚ²¼ôÂôÄ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Çà²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "»Ò²¼Ïâ±ßôÂôÄ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Çà²¼Ïâ±ßôÂôÄ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "½ð´´Ò©",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÆëÃ¼¹÷",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "°×²¼ºÚ±ßôÂôÄ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ËØ¼¦",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ËØÑ¼",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Çà²¼É®ÒÂ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÌúÊÖÕÆ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "»Æ²¼ôÂôÄ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "»¤·¨ôÂôÄ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Æ¤Ñü´ø",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "°Ù»¨¸¹Éß¸à",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÎÞÃû»¨",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "½ðÉßµ¨",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ë®ÃÛÌÒ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¸¹Éßµ¨",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÓÃ¹ýµÄ°Ù»¨¸¹Éß¸à",
                "quest_type":           "Ñ°",
                "time":                 700,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "ÐÛ»Æ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "°×³ñÈ¹",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "°×ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "°×Ë¿ÒÂ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Çà²¼ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "×íÏÉ²è",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "´Ö²¼ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÌÒ»¨¸â",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Êø·¢½ð´ø" ,
                "quest_type":           "Ñ°",
                "time":                 700,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "Ã÷Öé",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            16,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "ÌÒÄ¾½£",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "²¼ÕóÏä",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÓñÏô",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":            20,
                "pot_bonus":            16,
                "score" :               20
        ]),
        ([      "quest":                "½õºÐ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ïã",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÏãÂ¯",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÓÎÁú½£",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "Ï¸Ìú¸Ë",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ò©²Ý",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¾øÇé»¨",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            60,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "Ê¯¾Ê",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            60,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "ÒõÑôºÏºÍÉ¢",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":            60,
                "pot_bonus":            12,
                "score" :               20
        ]),
        ([      "quest":                "Å®¶ùÏã",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "°×É«µÀÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÎåÐÐ·þ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ïã²è",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "»ÆÉÀ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "²ñµ¶",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "À¯Öò",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Çå²è",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÊÖÅÁ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ê¯¿é",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ò¬×Ó",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÃÉº¹Ò©",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ð¡ÆÑÍÅ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ã×·¹",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "É³³æ",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "É³³æ¿Ç",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ñò±Þ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "³¤±Þ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "²¨Ë¹³¤ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¶¬²»À­",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ð¡Ã«Â¿",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "»ðÕÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "¹þÃÜ¹Ï",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÒÁÀçÂí",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÂíÄÌ¾Æºø",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "âÎ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Í­îà",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Í­¹Ä",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Í­ºÅ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "°¢À­²®Íäµ¶",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Î¬Îá¶û×å³¤ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÌìÉ½Ñ©Á«",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "»¨µñ¾Æ´ü",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ò©³ú",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÇåÐÄÉ¢",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÄñÓð´óë©",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "·¨ÂÖ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Ä¾¹÷",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "Å£Æ¤´ü",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "ÇàïýÃæ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "´äÂÌ³ñÉÀ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "½ðÏîÁ´",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "·Ûºì³ñÉÀ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
        ([      "quest":                "±ÌÂÝ´º",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":            60,
                "pot_bonus":            30,
                "score" :               20
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
