inherit SKILL;
mapping *quest = ({
      (["short":                "¥Û¿Ì±±√≈",
       "place" :              "/d/dali/northgate",]),  
      (["short":                "—Ô÷›√‹¡÷",
       "place" :              "/d/city/jiaowai5",]),  
     (["short":                "∂Î·“≤›≈Ô",
       "place" :              "/d/emei/caopeng",]),
     (["short":                "—Ô÷›Œ˜√≈",
       "place" :              "/d/city/ximen",]),
     (["short":                "—©…ΩÕ¡¬∑",
       "place" :              "/d/xueshan/tulu2",]),
     (["short":                "À’÷›¡Ù‘∞",
       "place" :              "/d/suzhou/liuyuan",]),
     (["short":                "À’÷›∫Æ…ΩÀ¬",
       "place" :              "/d/suzhou/hanshansi",]),
     (["short":                "∫º÷›∑…¿¥∑Â",
       "place" :              "/d/hangzhou/feilaifeng",]),
     (["short":                "∫º÷›æª¥»À¬",
       "place" :              "/d/hangzhou/jingcisi",]),
     (["short":                "∫º÷›¥‰Œ¢Õ§",
       "place" :              "/d/hangzhou/cuiweiting",]),
     (["short":                "∫º÷›æ€æ∞‘∞",
       "place" :              "/d/hangzhou/jujingyuan",]),
     (["short":                "√ÁΩÆ“◊œ™≤ø",
       "place" :              "/d/dali/yixibu",]),  
      (["short":                "—Ô÷›÷–—Îπ„≥°",
       "place" :              "/d/city/guangchang",]),  
      (["short":                "∫º÷›—ÿ∫˛¥Ûµ¿",
       "place" :              "/d/hangzhou/dadao1",]), 
      (["short":                "∫º÷›∂œ«≈",
       "place" :              "/d/hangzhou/duanqiao",]), 
      (["short":                "∫º÷›¡È“˛À¬",
       "place" :              "/d/hangzhou/lingyinsi",]), 
      (["short":                "–«Àﬁ∫£“¡¿Á",
       "place" :              "/d/xingxiu/beijiang",]), 
      (["short":                "Œ‰µ±»˝ÃÏ√≈",
       "place" :              "/d/wudang/santiangate",]), 
      (["short":                "∂Î·“ Æ∂˛≈Ã",
       "place" :              "/d/emei/shierpan3",]), 
      (["short":                "∂Î·“«ß∑‚÷",
       "place" :              "/d/emei/qianfoan",]), 
      (["short":                "∂Î·“æ≈ Ææ≈µ¿π’",
       "place" :              "/d/emei/jsjdg1",]), 
      (["short":                "√˜ΩÃ∫ÒÕ¡∆Ï√≈",
       "place" :              "/d/mingjiao/htqmen",]), 
      (["short":                "√˜ΩÃ¡“ª∆Ï∫Û√≈",
       "place" :              "/d/mingjiao/lhqhoumen",]), 
      (["short":                "∏£÷›∂´√≈",
       "place" :              "/d/fuzhou/dongmen",]), 
      (["short":                "∏£÷›±±¥ÛΩ÷",
       "place" :              "/d/fuzhou/beidajie",]), 
      (["short":                "–«Àﬁ∫£…≥ƒÆ",
       "place" :              "/d/xingxiu/shamo2",]),
      (["short":                "…Ÿ¡÷À¬ ØΩ◊",
       "place" :              "/d/shaolin/shijie4",]),
      (["short":                "œÂ—Ù ØΩ◊",
       "place" :              "/d/xiangyang/walle1",]),
      (["short":                "ª™…Ω‚©·¯≥Ó",
       "place" :              "/d/huashan/husun",]),
      (["short":                "ª™…Ω”Ò≈Æ∑Â",
       "place" :              "/d/huashan/yunu",]),
      (["short":                "ƒΩ»›–°æ∂",
       "place" :              "/d/mr/xiaojing1-2",]),
      (["short":                "ƒΩ»›¡¯ ˜¡÷",
       "place" :              "/d/mr/liulin",]),
      (["short":                "¥Û¿Ì¥Û∫ÕΩ÷",
       "place" :              "/d/dali/dahejiewest",]),
      (["short":                "À’÷›≥«±±√≈",
       "place" :              "/d/suzhou/beimen",]),
      (["short":                "À’÷›≥«–˛√Óπ€",
       "place" :              "/d/suzhou/xuanmiao",]),
      (["short":                "…Ÿ¡÷À¬…Ω√≈µÓ",
       "place" :              "/d/shaolin/smdian",]),
      (["short":                "…Ÿ¡÷À¬◊ﬂ¿»",
       "place" :              "/d/shaolin/zoulang7",]),
      (["short":                "Œ‰µ±…Ω¬∑",
       "place" :              "/d/wudang/shanlu3",]),
      (["short":                "…Ÿ¡÷À¬∞„»ÙÃ√æ≈≤ø",
       "place" :              "/d/shaolin/banruo9",]),
      (["short":                "—©…Ω…ΩΩ≈",
       "place" :              "/d/xueshan/shanjiao",]),
      (["short":                "∂Î·“æ≈¿œ∂¥",
       "place" :              "/d/emei/jiulaodong",]),
       (["short":                "∂Î·“π≈µ¬¡÷",
       "place" :              "/d/emei/gudelin1",]),
       (["short":                "∫Øπ≈πÿ",
       "place" :              "/d/city4/hanguguan",]),
       (["short":                "÷’ƒœ…Ωø⁄",
       "place" :              "/d/city4/zhongnan",]),
       (["short":                "√ˆΩ≠",
       "place" :              "/d/fuzhou/fzroad8",]),
       (["short":                "∫∫ÀÆƒœ∞∂",
       "place" :              "/d/shaolin/hanshui1",]),
       (["short":                "÷–Ãı…Ω√‹¡÷",
       "place" :              "/d/huashan/jzroad5",]),
       (["short":                "ÃÏ…ΩΩ≈œ¬",
       "place" :              "/d/xingxiu/shanjiao",]),
       (["short":                "ª™…ΩΩ≈œ¬",
       "place" :              "/d/huashan/path1",]),
       (["short":                "∆Ω∂®÷›",
       "place" :              "/d/heimuya/pingdingzhou",]),
       (["short":                "¬“ Ø∆¬",
       "place" :              "/d/heimuya/road1",]),      
       ([      "short":                "ª™…Ω¥Âƒœ¥Âø⁄",
                "place":                "/d/village/sexit",
        ]),([      "short":                "√ˆ∏”π≈µ¿",
                "place":                "/d/fuzhou/fzroad7",
        ]),([     "short":                "”Òª ∂•",
                 "place":               "/d/taishan/yuhuang",
         ]),([      "short":                "¡˘≈Ã…Ω",
                "place":                "/d/xingxiu/xxroad3",
        ]),([      "short":                "ÃÏ…Ω…Ω¬∑",
                "place":                "/d/xingxiu/tianroad1",
        ]),([      "short":                "ºŒ”¯πÿ",
                "place":                "/d/xingxiu/jiayuguan",
        ]),([      "short":                "Œ˜µ•±±¥ÛΩ÷",
                "place":                "/d/city2/xidan1",
        ]),([      "short":                "Œ‰µ¿≥°",
                "place":                "/d/city/wudao4",
        ]),([      "short":                "Õı∏ÆæÆ¥ÛΩ÷",
                "place":                "/d/city2/wangfu2",
        ]),([      "short":                "»´’ÊΩÃ±Æ",
                "place":                "/d/quanzhen/jiaobei",
        ]),([      "short":                "¿œÂ˝—“",
                "place":                "/d/gumu/juyan",
        ]),([      "short":                "¿œ¡˙Õ∑",
                "place":                "/d/guanwai/laolongtou",
        ]),([      "short":                "ºŒ–À≥«",
                "place":                "/d/quanzhou/jiaxing",
        ]),([      "short":                "—Ô÷›Œ˜√≈",
                "place":                "/d/city/ximen",
        ]),([      "short":                "œ…œº¡Î",
                "place":                "/d/fuzhou/fzroad1",
        ]),([      "short":                "ƒ˛‘∂",
                "place":                "/d/taishan/yitian",
        ]),([      "short":                "–°Õ¡Œ›",
                "place":                "/d/guanwai/tuwu",
        ]),([      "short":                "œ¬πÿ≥«",
                "place":                "/d/dali/xiaguan",
        ]),([      "short":                "¿Ó◊”Û‰ Ø¡÷",
                 "place":                "/d/dali/shilin1",
        ]),([      "short":                "¥Ûµ˛ÀÆ∆Ÿ≤º",
                 "place":                "/d/dali/dadieshui",
        ]),([      "short":                "¬ﬁŸ§µÈ",
                 "place":                "/d/dali/luojiadian",
        ]),([      "short":                "—Ù◊⁄’Ú",

                 "place":                "/d/dali/yangzong",
        ]),([      "short":                "Ã´ “„⁄",
                 "place":                "/d/songshan/taishique",
        ]),([      "short":                "…Ÿ¡÷ ØΩ◊",
                 "place":                "/d/shaolin/shijie7",
        ]),([      "short":                "Ã˙¡∫œø",
                 "place":                "/d/songshan/tieliang",
        ]),([      "short":                "æ˛º´Ï¯‘∫…Ω√≈",
                 "place":                "/d/songshan/junjigate",
        ]),([      "short":                "…Ò∫Ã‘≠",
                 "place":                "/d/gumu/shenheyuan",
        ]),([      "short":                "÷’ƒœ…Ω¥Û–£≥°",
                 "place":                "/d/gumu/daxiaochang",
        ]),([      "short":                "ΩÀ¯πÿ",
                 "place":                "/d/huashan/jinsuo",
        ]),([      "short":                "∆Ω–ƒ Ø",
                 "place":                "/d/huashan/pingxinshi",
        ]),([      "short":                "«ß≥ﬂ¥±",
                 "place":                "/d/huashan/qianchi",
        ]),([      "short":                "…Ω∫È∆Ÿ≤º",
                 "place":                "/d/huashan/shanhongpb",
        ]),([      "short":                "«Â“Ù∏Û",
                 "place":                "/d/emei/qingyinge",
        ]),([      "short":                " Æ∂˛≈Ã",
                 "place":                "/d/emei/shierpan1",
        ]),([      "short":                "æ≈¿œ∂¥ø⁄",
                 "place":                "/d/emei/jldongkou",
        ]),([      "short":                "æ≈ Ææ≈µ¿π’",
                 "place":                "/d/emei/jsjdg2",
        ]),([      "short":                "«ß∑‚÷",
                 "place":                "/d/emei/qianfoan",
        ]),([      "short":                "÷’ƒœ…Ωø’µÿ",
                 "place":                "/d/gumu/kongdi",
        ]),([      "short":                "÷’ƒœ…Ω÷˜∑Â",
                 "place":                "/d/gumu/zhufeng",
        ]),([      "short":                "–¸ÃÏ—¬",
                 "place":                "/d/mingjiao/shanlu3",
        ]), ([      "short":                "¡“ª∆Ï¥Û√≈",
                 "place":                "/d/mingjiao/lhqmen",
        ]),([      "short":                "—©…ΩÀ¬…Ω√≈",
                 "place":                "/d/xueshan/shanmen",
        ]),([      "short":                "∫ÈÀÆ∆Ï¥Û√≈",
                 "place":                "/d/mingjiao/hsqmen",
        ]),([      "short":                "∫ÈÀÆ∆Ï¥Û√≈",
                 "place":                "/d/mingjiao/hsqmen",
        ]),([      "short":                "±±¥ÛΩ÷",
                 "place":                "/d/city/beidajie2",
        ]),([      "short":                "«‡ Ø¥Ûµ¿",
                 "place":                "/d/wudang/wdroad1",
        ]),([      "short":                "πÿ¬Âµ¿",
                 "place":                "/d/city4/road1",
        ]),([      "short":                "¥ÛÊ‰µ¿",
                 "place":                "/d/taishan/yidao",
        ]),([      "short":                "πŸµ¿",
                 "place":                "/d/quanzhen/guandao2",]),
        (["short":                "∂´Ω÷",
        "place":                "/d/quanzhen/dongjie",]),
        (["short":                "∏ªº“¥Û√≈",
        "place":                "/d/quanzhen/fu-damen",]),
        (["short":                "…Ω¬∑",
        "place":                "/d/quanzhen/shanlu1",]),
        (["short":                "–°¥Â◊Ø",
        "place":                "/d/quanzhen/xiaocun",]),
        (["short":                "–«Àﬁ∫£",
        "place":                "/d/xingxiu/xxh2",]),
        (["short":                "ÃÏ…ΩΩ≈œ¬",
                 "place":                "/d/xingxiu/shanjiao",
        ]),([      "short":                "Àø≥Ò÷Æ¬∑",
                 "place":                "/d/xingxiu/silk2",

        ]),([      "short":                "≥§∞≤≥«Œ˜√≈",
                 "place":                "/d/city4/westgate",
        ]),([      "short":                "≥§∞≤≥«∂´√≈",
                 "place":                "/d/city4/eastgate",
        ]),([      "short":                "≥«∂´√≈",
                 "place":                "/d/city4/eastgate",
        ]),([      "short":                "…œÃÏÃ›",
                 "place":                "/d/huashan/shangtianti",
        ]),([      "short":                "Ω ˜¡÷",
                 "place":                "/d/xiaoyao/shulin3",
        ]),([      "short":                "ƒœ¥ÛΩ÷",
                 "place":                "/d/xiaoyao/shulin3",
        ]),      

   

      });

mapping query_quest()
{
  return quest[random(sizeof(quest))];
}
