mapping *persons=({
           ([    "name":"维新党人",
                 "id":"weixing dang",
                 "age":34,
                 "combat_exp":2000,
                 "skill":([
                     "unarmed":20,
                     "parry":20,
                     "dodge":20,
                     ]),
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",
             ]),
            ([     "name":"新撰组组员",
                   "id":"zhu yuan",
                   "age":23,
                   "combat_exp":500,
                   "skill":([
               "unarmed":10,
               "parry":10,
               "dodge":10,  ]),
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",

              ]),
            ([     "name":"维新志士",
                   "id":"zi shi",
                   "age":45,
                   "combat_exp":6000,
                   "skill":([
                "parry":40,
                "unarmed":40,
                "dodge":40,
                "blade":40,   ]),
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",
              ]),
            ([   "name":"外国水手",
                 "id":"shui shou",
                 "age":56,
                 "combat_exp":7000,
                 "skill":([
               "parry":50,
               "blade":50,
               "unarmed":50,
               "dodge":50,  ]),
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",
               ]),
             ([    "name":"奇兵队队员",
                   "id":"qibin dui",
                   "age":34,
                   "combat_exp":5000,
                   "skill":([
                 "parry":35,
                 "unarmed":35,
                 "dodge":35,
                 "whip":35,]),
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",

              ]),
             ([      "name":"日本街警",
                     "id":"jing cha",
                     "age":23,
                     "combat_exp":900,
                     "skill":([
                  "parry":20,
                  "unarmed":20,
                  "dodge":20,
                  "blade":20,]),
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",
               ]),
             ([       "name":"云游僧人",
                      "id":"yunyou seng",
                      "combat_exp":12000,
                      "age":56,
                      "skill":([
                   "parry":60,
                   "unarmed":60,
                   "dodge":60,]),
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",

               ]),
             ([       "name":"化缘僧",
                      "id":"huayuan seng",
                      "combat_exp":4000,
                      "age":30,
                      "skill":([
                   "parry":20,
                   "dodge":20,
                   "unarmed":20,]),
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",

                 ]),
             ([       "name":"风水术士",
                      "id":"fengshui shi",
                      "combat_exp":20000,
                      "age":67,
                      "skill":([
                   "parry":60,
                   "unarmed":60,
                   "dodge":60,]),
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",

                 ]),
              ([       "name":"行脚路人",
                       "id":"luren",
                       "combat_exp":5000,
                       "age":32,
                       "skill":([
                    "parry":43,
                    "unarmed":43,
                    "dodge":43,]),
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",

                 ]),
               ([       "name":"天主教教士",
                        "age":25,
                        "combat_exp":200,
                        "id":"jiao shi",
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",

                 ]),
               ([       "name":"清国留学生",
                        "id":"qingguo student",
                        "age":26,
                        "combat_exp":400,
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",

                 ]),
               ([      "name":"艺妓",
                       "id":"japan girl",
                       "gender":"女性",
                       "age":17,
                       "combat_exp":600,
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",

                    ]),
               ([       "name":"瞎子",
                        "id":"xia zi",
                        "age":45,
                        "combat_exp":7000,
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",

                    ]),
               ([       "name":"波斯商人",
                        "id":"shang ren",
                        "age":56,
                        "combat_exp":7000,
                    ]),
                ([      "name":"流浪儿",
                        "id":"liulang er",
                        "combat_exp":100,
                        "age":14,
                    ]),
               ([       "name":"小女孩",
                        "id":"nv hai",
                        "combat_exp":300,
                        "gender":"女性",
                        "age":15,
                  "cloth":"/clone/misc/cloth",
                  "weapon":"/clone/weapon/gangjian",

                    ]),
                ([       "name":"地痞",
                         "id":"di pi",
                         "combat_exp":2500,
                         "age":23,
                    ]),
                ([       "name":"日本歌妓",
                         "age":23,
                         "gender":"女性",
                         "id":"ge ji",
                         "combat_exp":12000,
                     ]),
               ([       "name":"老人",
                        "age":56,
                        "id":"lao ren",           
                        "combat_exp":7000,
                     ]),
            });
