inherit SKILL;
#include <ansi.h>;
//这是星星做来让新手熟悉地图用的任务
//npc happy收集
mapping *quest = ({
        ([      "quest":                "甄有庆",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "史镖头",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "陈阿婆",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "老朝奉",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "唐掌柜",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "小贼",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "鲁连荣",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "牙将",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "黄真",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "文泰来",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "阿拉木罕",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "买卖提",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "阿凡提",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "巴依",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "侯员外",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "刘菁",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "刘芹",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "刘夫人",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "刘正风",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "曲非烟",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "曲洋",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "骆冰",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "米为义",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "向大年",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "田伯光",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "仪琳",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "茶博士",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "西夏兵",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "李可秀",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "胡庆余",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "张召重",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "耶律齐",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "黄蓉",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "武三通",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "武修文",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "朱子柳",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "郭芙",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "木匠",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "偏将",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "佐将",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "宋兵",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "高丽商",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "书店老板",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "申人俊",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "武敦儒",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "吉人通",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "唐槐",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "刘虹瑛",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "萧飞",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "陈浒",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "龙铨",             "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "马五德",           "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "账房老夫子",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "本参",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "本相",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "本尘",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "本观",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "枯荣大师",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "本因",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "猎人",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "陪从",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "高升泰",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "素衣卫士",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "采笋人",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "士兵",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "族头人",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "侍从",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "大土司",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "歌女",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "何红药",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "薛老板",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "石匠",         "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "黄衣卫士",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "褚万里",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "傅思归",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "锦衣卫士",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "太监",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "宫女",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "神农帮弟子",   "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "无量剑弟子",   "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "凤一鸣",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "黄衣使者",   "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "渔夫",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "瘦商人",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "胖商人",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "凤七",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "张朝唐",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "张康",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "常金鹏",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "游讯",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "卜沉",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "沙天江",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "戈什哈",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "老和尚",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "林震南",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "余人彦",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "贾人达",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "崔镖头",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "阿碧",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "冯正东",     "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
        ([      "quest":                "阿朱",       "exp_bonus":random(20)+30,"pot_bonus": random(10)+10   ]),
});
mapping query_quest()
{
      return quest[random(sizeof(quest))];

}
