inherit SKILL;
#include <ansi.h>;
//这是星星做来让新手熟悉地图用的任务
//星星（lywin）2000/4/30
mapping *quest = ({
        ([      "quest":                "舞蛇人", "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "刀客",  "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "剑客",   "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "关安基",  "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "李力世",     "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "屠宰场伙计",   "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "小贩",       "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "贾老六",     "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "游客",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "游方和尚",   "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "胡掌柜",     "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "江湖豪客",   "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "高彦超",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "小流氓",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "地痞",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "掌柜",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "客店伙计",    "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "吴六奇",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "瘦头陀",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "书生",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "顾炎武",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "萧远山",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "冯锡范",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "太监",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "卖花姑娘",    "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "侍卫",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "白龟寿",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "钱老本",       "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "土匪",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "挑夫",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "贡唐仓国师",  "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "徐天川",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "桑三娘",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "沈青刚",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "马青雄",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "吴青烈",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "薛慕华",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "康广陵",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "蒙面人",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "苏星河",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "苟读",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "钱青健",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "彭连虎",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "陆冠英",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "裘千丈",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "翠花",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "地保",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "李四",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "沙通天",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "梁子翁",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "侯通海",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "大汉",       "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "老者",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "老鸨婆",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "老和尚",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "程老板",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "乐厚",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "天松道人",    "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "天柏道人",    "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "祖千秋",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "单正",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "天乙道人",    "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "小孩",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "虚通",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "虚明",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "李莫愁",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "定静师太",    "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "仪文",        "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "冯铁匠",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
        ([      "quest":                "老船夫",      "exp_bonus":random(15)+30,"pot_bonus": random(8)+10   ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];

}
