// 门派武功列表 (by xbd)

mapping *ps = ({
	([	"party": "baituo",
		"status": ([
			"party": "baituo",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"hamagong": 100,
			"training": 200,
			"chanchu-bufa": 100,
			"shexing-diaoshou": 100,
			"hamashengong": 100,
                        "lingshe-quan": 100,
                        "lingshe-zhangfa": 100,
			"qixuan-wuxingjian": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "hamagong",
			"dodge": "chanchu-bufa",
			"strike": "hamashengong",
                        "cuff": "lingshe-quan",
			"staff": "lingshe-zhangfa",
			"parry": "lingshe-zhangfa",
                        "unarmed": "shexing-diaoshou",
			"hand": "shexing-diaoshou",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "emei",
		"status": ([
			"party": "emei",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"lingji-zhuang": 100,
			"mahayana": 200,
                        "persuading": 200,
			"zhutian-bu": 100,
			"yanxing-dao": 100,
			"huifeng-jian": 100,
			"jinding-zhang": 100,
                        "bagua-zhang": 100,
                        "bagua-dao": 100,
			"tiangang-zhi": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "lingji-zhuang",
			"dodge": "zhutian-bu",
			"finger": "tiangang-zhi",
			"strike": "jinding-zhang",
                        "blade": "yanxing-dao",
			"sword": "huifeng-jian",
			"parry": "huifeng-sword",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "xiaoyao",
		"status": ([
			"party": "xiaoyao",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"bahuang-gong": 100,
			"beiming-shengong": 100,
			"yangyanshu": 200,
			"lingboweibu": 100,
			"zhemei-shou": 100,
			"liuyang-zhang": 100,
			"tianyu-qijian": 100,
                        "panyang-zhang": 100,
                        "qingyun-shou": 100
			"ruyi-dao": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "beiming-shengong",
			"dodge": "lingboweibu",
			"unarmed": "zhemei-shou",
			"strike": "liuyang-zhang",
			"sword": "tianyu-qijian",
			"blade": "ruyi-dao",
			"parry": "lingboweibu",]),
		"skill_prepare": ([
			"unarmed": "zhemei-shou",
			"strike": "liuyang-zhang",]),
	]),
	([	"party": "mizong",
		"status": ([
			"party": "xueshan",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"longxiang-banruo": 100,
			"xiaowuxiang": 100,
			"lamaism": 200,
                        "necromancy": 200,
			"yujiamu-quan": 100,
			"tanzhi-shentong": 100,
			"dashou-yin": 100,
			"huoyan-dao": 100,
			"xiangmo-chu": 100,
                        "shenkong-xing": 100,
                        "xue-dao": 100,
                        "riyue-lun": 100,
			"mingwang-jian": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "xiaowuxiang",
			"dodge": "shenkong-xing",
			"unarmed": "yujiamu-quan",
			"strike": "huoyan-dao",
			"cuff": "yujiamu-quan",
                        "staff": "xiangmo-chu",
			"hand": "dashou-yin",
			"sword": "mingwang-jian",
			"parry": "huoyan-dao",]),
		"skill_prepare": ([
			"cuff": "yujiamu-quan",
			"hand": "dashou-yin",]),
	]),
	([	"party": "xingxiu",
		"status": ([
			"party": "xingxiu",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"huagong-dafa": 100,
			"poison": 200,
			"zhaixinggong": 100,
			"sanyin-wugongzhao": 100,
			"feixing-shu": 100,
			"chanhun-suo": 100,
			"tianshan-zhang": 100,
			"chousui-zhang": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "huagong-dafa",
			"dodge": "zhaxinggong",
			"strike": "chousui-zhang",q
			"claw": "sanying-wugongzhao",
			"throwing": "feixing-shu",
			"staff": "tianshan-zhang",
			"whip": "chanhun-suo",
			"parry": "chousui-zhang",]),
		"skill_prepare": ([
			"strike": "chousui-zhang",
			"claw": "sanying-wugongzhao",]),
	]),
	([	"party": "feitian",
		"status": ([
			"party": "feitian",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"shayi-xinfa": 100,
			"shayi": 200,
			"wuxing-dun": 100,
			"aikido": 100,
			"xuanhualiu-quanfa": 100,
			"shiren-quanfa": 100,
			"shiren-jianfa": 100,
      "feitian-yujianliu": 100,
			"huoxinliu-jianfa": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "shayi-xinfa",
			"dodge": "wuxing-dun",
			"unarmed": "xuanhualiu-quanfa",
			"cuff": "shiren-quanfa",
			"blade": "feitian-yujianliu",
			"parry": "feitian-yujianliu",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "shenlong",
		"status": ([
			"party": "shenlong",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"shenlong-xinfa": 100,
			"zhaosheshu": 200,
			"yixingbu": 100,
			"shenlong-bashi": 100,
			"shedao-qigong": 100,
			"huagu-mianzhang": 100,
			"shenlong-tuifa": 100,
			"dulong-shenzhua": 100,
			"xuanming-zhang": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "shenlong-xinfa",
			"dodge": "yixingbu",
			"strike": "huagu-mianzhang",
			"hand": "shenlong-bashi",
			"claw": "dulong-shenzhua",
			"staff": "shedao-qigong",
			"parry": "shenlong-bashi",
			"leg": "shenlong-tuifa",]),
		"skill_prepare": ([
			"strike": "huagu-mianzhang",
			"hand": "shenlong-bashi",]),
	]),
	([	"party": "tangmen",
		"status": ([
			"party": "tangmen",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"biyun-xinfa": 100,
			"qiulinshiye": 100,
			"zimu-zhen": 100,
			"biye-wu": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "biyun-xinfa",
			"dodge": "qiulinshiye",
			"unarmed": "biye-wu",
			"strike": "biye-wu",
                        "throwing": "zimu-zhen",
			"parry": "zimu-zhen",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "riyue",
		"status": ([
			"party": "riyue",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"kuihua-xinfa": 100,
			"kuihua-dafa": 100,
			"kuihua-feiying": 100,
			"pixie-jian": 100,
                        "tmdafa": 200,
			"changquan": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "kuihua-xinfa",
			"dodge": "kuihua-feiying",
			"unarmed": "changquan",
			"sword": "kuihua-dafa",
			"parry": "kuihua-dafa",]),
		"skill_prepare": ([ ]),
        ]),
	
	([	"party": "mizong1",
		"status": ([
			"party": "mizong1",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"longxiang-banruo": 100,
			"xiaowuxiang": 100,
			"lamaism": 200,
                        "necromancy": 200,
			"yujiamu-quan": 100,
			"tanzhi-shentong": 100,
			"dashou-yin": 100,
			"huoyan-dao": 100,
			"xiangmo-chu": 100,
                        "shenkong-xing": 100,
                        "xueshitiao": 100,
                        "xue-dao": 100,
                        "riyue-lun": 100,
			"mingwang-jian": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "longxiang-banruo",
			"dodge": "shenkong-xing",
			"unarmed": "yujiamu-quan",
			"strike": "huoyan-dao",
			"cuff": "yujiamu-quan",
                        "hammer": "riyue-lun",
			"hand": "dashou-yin",
			"sword": "mingwang-jian",
			"parry": "riyue-lun",]),
		"skill_prepare": ([
			"cuff": "yujiamu-quan",
			"hand": "dashou-yin",]),
	]),
	        "party": "shaolin",
		"status": ([
			"party": "shaolin",
			"no_accept": 1,
			"no_fight": 1,
			"no_weapon": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"hunyuan-yiqi": 100,
			"buddhism": 200,
			"shaolin-shenfa": 100,
			"nianhua-zhi": 100,
			"sanhua-zhang": 100,
			"fengyun-shou": 100,
                        "longzhua-gong": 100,
                        "weituo-zhang": 100,
                        "shaolin-tantui": 100,                        
                        "jingang-zhang": 100,
                        "jimie-zhua": 100,
                        "duoluoye-zhi": 100,
                        "mohe-zhi": 100,
                        "boluomi-shou": 100,
                        "yijinjing": 100,
                        "cibei-dao": 100,
                        "damo-jian": 100,
                        "luohan-quan": 100,
                        "pudu-zhang": 100,             
                        "qianye-shou": 100,
                        "riyue-bian": 100, 
                        "weituo-gun": 100,
                        "wuchang-zhang": 100,
			"banruo-zhang": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "yijinjing",
			"dodge": "shaolin-shenfa",
			"finger": "nianhua-zhi",
			"cuff": "luohan-quan",
			"strike": "sanhua-zhang",
                        "hand": "fengyun-shou",
                        "blade": "cibei-dao",
                        "club": "wuchang-zhang",
                        "staff": "weituo-gun",
                        "sword": "wuying-jian",
                        "whip": "riyue-bian",
                        "claw": "longzhua-gong",
			"parry": "nianhua-zhi",]),
		"skill_prepare": ([
			"finger": "nianhua-zhi",
			"strike": "sanhua-zhang",]),
	]),
	([	"party": "riyue1",
		"status": ([
			"party": "riyue1",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"kuifa-xinfa": 100,
			"changquan": 100,
			"lingxu-bu": 100,
			"taishan-sword": 100,
			"huifeng-jian": 100,
			"taiji-jian": 100,
                        "hengshan-jian": 100,
                        "huashan-sword": 100,
                        "songshan-jian": 100,
                        "tmzhang": 100,
                        "tmjian": 100,
                        "tmdao": 100,
                        "tmdafa": 100,
                        "pmshenfa": 100,
			"damo-jian": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "tmdafa",
			"dodge": "pmshenfa",
			"unarmed": "tmzhang",
			"blade": "tmdao",
			"sword": "tmjian",
			"parry": "tmjian",]),
		"skill_prepare":([ ]),
	]),
});
