// 门派武功列表 (by xbd)

mapping *ps = ({
	([	"party": "wudang",
		"status": ([
			"party": "wudang",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"taiji-shengong": 100,
			"taoism": 200,
			"tiyunzong": 100,
			"taiji-quan": 100,
			"taiji-jian": 100,
			"wudang-array": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "taiji-shengong",
			"dodge": "tiyunzong",
			"unarmed": "taiji-quan",
			"sword": "taiji-jian",
			"parry": "taiji-quan",
			"array": "wudang-aray",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "huashan",
		"status": ([
			"party": "huashan",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"zixia-shengong": 100,
			"zhengqijue": 200,
			"feiyan-huixiang": 100,
			"poyu-quan": 100,
			"hunyuan-zhang": 100,
			"lonely-sword": 100,
			"huashan-sword": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "zixia-shengong",
			"dodge": "feiyan-huixiang",
			"unarmed": "poyu-quan",
			"strike": "hunyuan-zhang",
			"sword": "lonely-sword",
			"parry": "lonely-sword",]),
		"skill_prepare": ([
			"unarmed": "poyu-quan",
			"strike": "hunyuan-zhang",]),
	]),
	([	"party": "lingjiu",
		"status": ([
			"party": "lingjiu",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"bahuang-gong": 100,
			"beiming-shengong": 100,
			"yangyanshu": 200,
			"lingboweibu": 100,
			"zhemei-shou": 100,
			"liuyang-zhang": 100,
			"tianyu-qijian": 100,
			"ruyi-dao": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "bahuang-gong",
			"dodge": "lingboweibu",
			"unarmed": "zhemei-shou",
			"strike": "liuyang-zhang",
			"sword": "tianyu-qijian",
			"blade": "ruyi-dao",
			"parry": "lingboweibu",]),
		"skill_prepare": ([
			"unarmed": "zhemei-shou",
			"strike": "liuyang-zhang",]),
	]),
	([	"party": "taohua",
		"status": ([
			"party": "taohua",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"bibo-shengong": 100,
			"qimen-wuxing": 200,
			"count": 200,
			"anying-fuxiang": 100,
			"tanzhi-shentong": 100,
			"lanhua-shou": 100,
			"luoying-zhang": 100,
			"xuanfeng-leg": 100,
			"yuxiao-jian": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "bibo-shengong",
			"dodge": "anying-fuxiang",
			"unarmed": "xuanfeng-leg",
			"strike": "luoying-zhang",
			"finger": "tanzhi-shentong",
			"hand": "lanhua-shou",
			"sword": "yuxiao-jian",
			"parry": "yuxiao-jian",]),
		"skill_prepare": ([
			"finger": "tanzhi-shentong",
			"hand": "lanhua-shou",]),
	]),
	([	"party": "tiandihui",
		"status": ([
			"party": "tiandihui",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"yunlong-shengong": 100,
			"yunlong-xinfa": 200,
			"yunlong-shenfa": 100,
			"yunlong-zhua": 100,
			"yunlong-shou": 100,
			"houquan": 100,
			"yunlong-jian": 100,
			"yunlong-bian": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "yunlong-shengong",
			"dodge": "yunlong-shenfa",
			"unarmed": "houquan",
			"claw": "yunlong-zhua",
			"hand": "yunlong-shou",
			"sword": "yunlong-jian",
			"whip": "yunlong-bian",
			"parry": "yunlong-jian",]),
		"skill_prepare": ([
			"claw": "yunlong-zhua",
			"hand": "yunlong-shou",]),
	]),
	([	"party": "mingjiao",
		"status": ([
			"party": "mingjiao",
			"family/family_name": "明教",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"jiuyang-shengong": 100,
			"shenghuo-shengong": 100,
			"qiankun-danuoyi": 100,
			"qingfu-shenfa": 100,
			"qishang-quan": 100,
			"hanbing-mianzhang": 100,
			"sougu": 100,
			"shenghuo-ling": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "jiuyang-shengong",
			"dodge": "qingfu-shenfa",
			"unarmed": "qishang-quan",
			"strike": "hanbing-mianzhang",
			"claw": "sougu",
			"sword": "shenghuo-ling",
			"parry": "qiankun-danuoyi",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "gumu",
		"status": ([
			"party": "gumu",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"yunv-xinfa": 100,
			"qufeng": 200,
			"yunv-shenfa": 100,
			"anranxiaohun-zhang": 100,
			"meinv-quan": 100,
			"tianluo-diwang": 100,
			"yunv-jian": 100,
			"quanzhen-jian": 100,
			"xuantie-sword": 100,
			"qixing-array": 200,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "yunv-xinfa",
			"dodge": "yunv-shenfa",
			"unarmed": "anranxiaohun-zhang",
			"strike": "tianluo-diwang",
			"cuff": "meinv-quan",
			"sword": "yunv-jian",
			"parry": "yunv-jian",
			"array": "qixing-array",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "gaibang",
		"status": ([
			"party": "gaibang",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"huntian-qigong": 100,
			"begging": 200,
			"xiaoyaoyou": 100,
			"xianglong-zhang": 100,
			"dagou-bang": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "huntian-qigong",
			"dodge": "xiaoyaoyou",
			"unarmed": "xianglong-zhang",
			"staff": "dagou-bang",
			"parry": "dagou-bang",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "quanzhen",
		"status": ([
			"party": "quanzhen",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"xiantian-qigong": 100,
			"taoism": 200,
			"jinyan-gong": 100,
			"haotian-zhang": 100,
			"sun-finger": 100,
			"quanzhen-jian": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "xiantian-qigong",
			"dodge": "jinyan-gong",
			"strike": "haotian-zhang",
			"finger": "sun-finger",
			"sword": "quanzhen-jian",
			"parry": "quanzhen-jian",]),
		"skill_prepare": ([
			"strike": "haotian-zhang",
			"finger": "sun-finger",]),
	]),
	([	"party": "dali",
		"status": ([
			"party": "dali",
			"no_accept": 1,
			"no_fight": 1,
			"no_weapon": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"kurong-changong": 100,
			"buddhism": 200,
			"tiannan-step": 100,
			"six-finger": 100,
			"sun-finger": 100,
			"yiyang-zhi": 100,
			"duanjia-sword": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "kurong-changong",
			"dodge": "tiannan-step",
			"unarmed": "six-finger",
			"finger": "sun-finger",
			"sword": "duanjia-sword",
			"parry": "six-finger",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "tiezhang",
		"status": ([
			"party": "tiezhang",
			"no_accept": 1,
			"no_fight": 1,
			"no_weapon": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"guiyuan-tunafa": 100,
			"shuishangpiao": 100,
			"tiezhang-zhangfa": 100,
			"duanyun-fu": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "guiyuan-tunafa",
			"dodge": "shuishangpiao",
			"unarmed": "tiezhang-zhangfa",
			"strike": "tiezhang-zhangfa",
			"axe": "duanyun-fu",
			"parry": "tiezhang-zhangfa",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "murong",
		"status": ([
			"party": "murong",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"shenyuan-gong": 100,
			"douzhuan-xingyi": 100,
			"yanling-shenfa": 100,
			"canhe-zhi": 100,
			"xingyi-zhang": 100,
			"murong-jianfa": 100,
			"murong-daofa": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "shenyuan-gong",
			"dodge": "yanling-shenfa",
			"finger": "canhe-zhi",
			"strike": "xingyi-zhang",
			"sword": "murong-jianfa",
			"blade": "murong-daofa",
			"parry": "douzhuan-xingyi",]),
		"skill_prepare": ([
			"finger": "canhe-zhi",
			"strike": "xingyi-zhang",]),
	]),
	([	"party": "kunlun",
		"status": ([
			"party": "kunlun",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"xuantian-wuji": 100,
			"art": 200,
			"kunlun-shenfa": 100,
			"kunlun-zhang": 100,
			"chuanyun-tui": 100,
			"zhentian-quan": 100,
			"liangyi-jian": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "xuantian-wuji",
			"dodge": "kunlun-shenfa",
			"strike": "kunlun-zhang",
			"unarmed": "chuanyun-tui",
			"cuff": "zhentian-quan",
			"sword": "liangyi-jian",
			"parry": "liangyi-jian",]),
		"skill_prepare": ([
			"unarmed": "chuanyun-tui",
			"cuff": "zhentian-quan",]),
	]),
	([	"party": "lingxiao",
		"status": ([
			"party": "lingxiao",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"bingxue-xinfa": 100,
			"snowstep": 100,
			"snow-zhang": 100,
			"xueshan-sword": 100,
			"jinwu-blade": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "bingxue-xinfa",
			"dodge": "snowstep",
			"unarmed": "snow-zhang",
			"sword": "xueshan-sword",
			"blade": "jinwu-blade",
			"parry": "xueshan-sword",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "wdjiao",
		"status": ([
			"party": "wdjiao",
			"family/family_name": "五毒教",
			"no_accept": 1,
			"no_fight": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"wudu-shengong": 100,
			"duji": 200,
			"wudu-yanluobu": 100,
			"qianzhu-wandushou": 100,
			"wudu-goufa": 100,
			"wudu-bian": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "wudu-shengong",
			"dodge": "wudu-yanluobu",
			"unarmed": "qianzhu-wandushou",
			"sword": "wudu-goufa",
			"whip": "wudu-bian",
			"parry": "wudu-goufa",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "noname",
		"status": ([
			"party": "noname",
			"no_accept": 1,
			"no_fight": 1,
			"no_weapon": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"taixuan-gong": 100,
			"canzhi-duanhun": 100,
			"chuixue-jian": 100,
			"luohua-jian": 100,
			"wushuang-jian": 100,
			"liancheng-jian": 100,
			"hujia-daofa": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "taixuan-gong",
			"dodge": "taixuan-gong",
			"unarmed": "canzhi-duanhun",
			"sword": "luohua-jian",
			"blade": "hujia-daofa",
			"parry": "taixuan-gong",]),
		"skill_prepare": ([ ]),
	]),
	([	"party": "jiuyin",
		"status": ([
			"party": "jiuyin",
			"no_accept": 1,
			"no_fight": 1,
			"jiuyin/full": 1,
			"no_weapon": 1,
			"ticks": ([ ]),
			"combat_mode": 0,]),
		"skills": ([
			"jiuyin-zhengong": 100,
			"daode-jing": 200,
			"jiuyin-shenfa": 100,
			"jiuyin-shenzhua": 100,
			"jiuyin-shenzhang": 100,
			"dafumo-quan": 100,
			"xuanyin-jian": 100,
			"yinlong-bian": 100,]),
		"learned": ([ ]),
		"skill_map": ([
			"force": "jiuyin-zhengong",
			"dodge": "jiuyin-shenfa",
			"unarmed": "dafumo-quan",
			"strike": "jiuyin-shenzhang",
			"claw": "jiuyin-shenzhua",
			"sword": "xuanyin-jian",
			"whip": "yinlong-bian",
			"parry": "xuanyin-jian",]),
		"skill_prepare": ([
			"unarmed": "dafumo-quan",
			"strike": "jiuyin-shenzhang",]),
	]),
});
